### ISSUE TITLE
Invalid version 2.0.0-RC1 uploaded to Supermarket

### ISSUE THREAD

**Issue by robbkidd** [Cognifide/aet-cookbook#12]
Hello, @wiiitek! We've seen the errors you were probably seeing after uploading version `2.0.0-RC1` of this cookbook to the [public Supermarket](https://supermarket.chef.io).

Cookbook metadata does not support appending more characters after the numerics. [Cookbook versions must be either X.Y or X.Y.Z](https://docs.chef.io/cookbook_versions.html#constraints). I see that [the version in metadata.rb at the current master](https://github.com/Cognifide/aet-cookbook/blob/4d3cf97dce9ae9054000aa38ca62098103ad1060/metadata.rb#L7) is `2.0.0` which is valid. The best option I can think of at the moment to get you unstuck is for us (Supermarket admins) to delete the `2.0.0-RC1` version from the Supermarket. You could then upload version `2.0.0` from your master branch.

Obviously this is a a failing in the chain of tools that should have warned you of this version format constraint before accepting your uploaded cookbook. I'll be adding an issue to our backlog to provide a better failure error at upload time instead of allowing an invalid version to be added to the system.

You can find me on the [Chef Community Slack](http://community-slack.chef.io/) if you would like to talk about this faster than over a GitHub issue!

**Comment by wiiitek** [comment]
Thank you @robbkidd and also thank you for the Email you've sent.
I will upload the correct version (2.0.0) tommorow.

Closing this issue as the failing version was removed from Supermarket.
