### ISSUE TITLE
AET virtual host template can't be changed in a wrapper cookbook

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/aet-cookbook#4]
Current implementation assumes that Apache virtual host file always gets rendered out of a [template](https://github.com/Cognifide/aet-cookbook/blob/master/recipes/deploy_reports.rb#L92-L99) provided by aet cookbook. 

Sometimes it's required to introduce a change in that vhost file, i.e. change proxy rules for `/api` location.

Unfortunately it's not possible to inject custom template, unless you want to use some nasty Chef tricks. It's not a big deal if there's a web server layer in front of that Apache, however it can become a blocker for some users.

`cookbook` property defined as an attribute should make it way more customizable:

```ruby
# attribute file
default['aet']['apache']['vhost_template_cookbook'] = 'aet'

# recipe file
template '/etc/httpd/sites-available/aet.conf' do
  source 'etc/httpd/sites-available/aet.conf.erb'
  cookbook node['aet']['apache']['vhost_template_cookbook']
  owner 'root'
  group 'root'
  mode 0644
  notifies :restart, 'service[apache2]', :delayed
end
```

**Comment by karoldrazek** [comment]
Template source configuration added in v1.4.13
